version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vue-app
    ports:
      - "3000:80" # Port harus dalam format string

  nginx:
    image: nginx:alpine
    container_name: nginx-app
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - app
